apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  labels:
    app: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: docker:dind
        ports:
        - containerPort: 2376
          name: docker-tcp
        - containerPort: 8888
          name: docker-http
        env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
        volumeMounts:
        - name: jenkins-docker-certs
          mountPath: /certs/client
        securityContext:
          privileged: true
      volumes:
      - name: jenkins-docker-certs
        persistentVolumeClaim:
          claimName: jenkins-docker-certs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: docker
spec:
  selector:
    app: docker
  ports:
  - protocol: TCP
    port: 2376
    targetPort: 2376
    name: docker-tcp
  - protocol: TCP
    port: 8888
    targetPort: 8888
    name: docker-http
  type: NodePort
