apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins 
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: ahussain146/custom-jenkins:latest
        ports:
        - containerPort: 8080
          name: jenkins-http
        - containerPort: 50000
          name: jenkins-agent
        env:
        - name: DOCKER_HOST
          value: tcp://docker:2376
        - name: DOCKER_CERT_PATH
          value: /certs/client
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: GIT_REPO_URL
          value: "https://github.com/AhCap146/welcome-api.git"
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        - name: jenkins-docker-certs
          mountPath: /certs/client
        - name: kubeconfig  # Mount the kubeconfig file
          mountPath: /var/jenkins_home/.kube/config
          subPath: config
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-data-pvc
      - name: jenkins-docker-certs
        persistentVolumeClaim:
          claimName: jenkins-docker-certs-pvc
      - name: kubeconfig  # Define the volume for kubeconfig
        secret:
          secretName: jenkins-kubeconfig
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: jenkins-http
  - protocol: TCP
    port: 50000
    targetPort: 50000
    name: jenkins-agent
  type: NodePort
